// <auto-generated />
namespace BiraFit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class personaltraineridsportleridkonversation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personaltraineridsportleridkonversation));
        
        string IMigrationMetadata.Id
        {
            get { return "201704101041178_personaltrainerid-sportlerid-konversation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
