language: csharp
solution: BiraFit.sln
install:
  - nuget restore BiraFit.sln
  - nuget install xunit.runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BiraFit.sln
  - mono ./testrunner/xunit.runners*/tools/xunit.console.clr4.exe ./BiraFitTest/bin/Debug/BiraFitTest.dll